server.port=8080
spring.application.name=vectrasync

spring.threads.virtual.enabled=true

vaadin.launch-browser=false
vaadin.productionMode=false

spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

logging.level.com.vectrasync=DEBUG
logging.level.root=INFO
logging.file.name=logs/vectrasync.log
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{40} - %msg%n
